--- #YAML:1.0
name:                Math-ConvexHull
version:             1.02
abstract:            Calculate convex hulls using Graham's scan (n*log(n))
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steffen Mueller <smueller@cpan.org>
