--- #YAML:1.0
name:                Math-ConvexHull
version:             1.03
abstract:            Calculate convex hulls using Graham's scan (n*log(n))
license:             perl
author:              
    - Steffen Mueller <smueller@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
